### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by galoisgroupcn** [junyanz/CycleGAN#118]
@junyanz 
Hello Dr. Zhu!

I'm quite impressed by your work. Do you think this repo can be successfully run on Google Colab?

Problem is, Colab goes with CUDA 10 (cannot downgrade) which does not work with Torch. There's a way to build Torch with CUDA 10 though, but must be hard to implement on Colab.

https://github.com/torch/cutorch/issues/834

-- Do you think Nvidia GTX 1050 (2GB RAM) can run this repo?

Look forward to your reply.

Thank you,

Amber Ji

**Comment by junyanz** [comment]
- Colab: There is a [Colab](https://colab.research.google.com/drive/1Enc-pKlP4Q3cimEBfcQv0B_6hUvjVL3o?sandboxMode=true) for CycleGAN. 
- GTX 1050 (2GB) might not be enough. I will recommend a GPU with 8GB++.

**Comment by israrbacha** [comment]
Hello junyanz,
i am doing my research in I2I translation. i am planning to use your model as a baseline. but i am confused about the improvement because a lot of work is done already like MUNIT and some other disentangling methods. do you have any suggestion or advice for me? like how to improve.

**Comment by israrbacha** [comment]
Hello Mr.junyanz
i am doing my master's research in I2I using GANs, i am planning to use cycleGAN as a baseline model but i am confused about the improvements because alot of work is done in this side like multi-model image2image translaton which disentangle the content style latent space and many more. do you have any suggestion for me like how to improve? thanks

**Comment by junyanz** [comment]
These are all good ideas. I don't have a concrete idea on how to improve at this moment.
