### ISSUE TITLE
Fatal error when running test in CPU only mode.

### ISSUE THREAD

**Issue by armoreal** [junyanz/CycleGAN#12]
First of all CycleGAN show awesome results when running on GPU.
But I was unable to generate bigger image using CPU.

`DATA_ROOT=./datasets/m name=style_cezanne_pretrained model=one_direction_test phase=test loadSize=500 fineSize=500 resize_or_crop="scale_width"  gpu=0 cudnn=0 th test.lua`

`/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <torch.CudaTensor>
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
        /root/torch/install/share/lua/5.1/nn/Module.lua:184: in function 'read'
        /root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
        /root/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
        /root/CycleGAN/util/util.lua:192: in function 'load_test_model'
        ./models/one_direction_test_model.lua:23: in function 'Initialize'
        test.lua:80: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670`

**Comment by taesung89** [comment]
Hi Armoreal, while we work on this issue, you can remove `cudnn=0`, if you could install cudnn package. 

`DATA_ROOT=./datasets/m name=style_cezanne_pretrained model=one_direction_test phase=test loadSize=500 fineSize=500 resize_or_crop="scale_width" gpu=0 th test.lua`

The bug seems to appear because the pretrained model was trained using GPUs, and torch.load() cannot load a model trained on GPU without cudnn package.. We will investigate this more.
