### ISSUE TITLE
Correct learning model and the size of the photo at the output

### ISSUE THREAD

**Issue by AntDev95** [junyanz/CycleGAN#19]
I understand that to get the output of a photo size of 512x512 should I train it on 512x512?

For example, before learning, change the size in options.lua display_winsize to 512?
Or is it not necessary?

Just like now I get this error:
`./models/cycle_gan_model.lua:109: bad argument #1 to 'copy' (sizes do not match at /root/torch/extra/cutorch/lib/THC/generic/THCTensorCopy.c:48)
stack traceback:
	[C]: in function 'copy'
	./models/cycle_gan_model.lua:109: in function 'Forward'
	test.lua:101: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
`

I do this:
DATA_ROOT=./datasets/faces name=face_model phase=test loadSize=128 fineSize=512 resize_or_crop="scale_width" th test.lua

sorry, this google translate ¯ \ _ (ツ) _ / ¯

**Comment by junyanz** [comment]
You can use loadSize=512, and fineSize=512, and I am not sure if your training can fit into the GPU memory. Instead, you can train your model on 360x360 (or even smaller) cropped images, and you are still able to test it on 512x512 images. I will suggest you set loadSize=512 and fineSize=360.

**Comment by AntDev95** [comment]
When you run this command:
`DATA_ROOT=./datasets/faces name=faces_model phase=test loadSize=512 fineSize=512 th test.lua`

As a result, I get this:

```
THCudaCheck FAIL file=/root/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
In 1 module of nn.ConcatTable:
In 2 module of nn.Sequential:
/root/torch/install/share/lua/5.1/nn/THNN.lua:110: cuda runtime error (2) : out of memory at /root/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:66
stack traceback:
	[C]: in function 'v'
	/root/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialConvolutionMM_updateOutput'
	/root/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:79: in function </root/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:76>
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </root/torch/install/share/lua/5.1/nn/Sequential.lua:41>
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function </root/torch/install/share/lua/5.1/nn/ConcatTable.lua:9>
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	/root/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/root/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	./models/cycle_gan_model.lua:114: in function 'Forward'
	test.lua:101: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	/root/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/root/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	./models/cycle_gan_model.lua:114: in function 'Forward'
	test.lua:101: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
```

**Comment by AntDev95** [comment]
Does this mean there is not enough memory in my GPU?
Please tell me the configuration of the server you are using for these tasks.

Thank you

**Comment by taesung89** [comment]
Hi AntDev95, 

We used GTX1080s and Titan X (Pascal), which have 8GB and 12GB of memory. I think 512x512 doesn't fit in one gpu if you use `cycle_gan_model.lua`, because it loads two generator-discriminator pair onto the GPU memory. Fortunately, during test time you can generate larger images by loading only one generator. This can be done in choosing `one_direction_test_model.lua`. For example, you can do

`DATA_ROOT=./datasets/ae_photos name=style_cezanne_pretrained model=one_direction_test phase=test loadSize=256 fineSize=256 resize_or_crop="scale_width" th test.lua`

as it appeared in README.md. 

To reiterate, when you train, you have to allocate memory for the discriminator and the generator in both directions, so you need to train on 360x360 cropped regions. During test time, you can generate larger images by loading only one generator, which can be achieved by using `one_direction_test_model`.

**Comment by AntDev95** [comment]
Thank you very much for your help.

**Comment by thelittlekid** [comment]
I'm not sure if this is the right place to post, it seems to be the most relavant issue. 
When I tried to load one generator during test time for larger images, I got the following error: 
`model not found!    .../Documents/CycleGAN-master/checkpoints/styleA2styleB/latest_net_G.t7	
.../torch/install/bin/luajit: ./models/one_direction_test_model.lua:49: attempt to index field 'netG_A' (a nil value)`
I guess the reason is that instead of latest_net_G.t7, I got two generators latest_net_G_A.t7 and latest_net_G_B.t7 after training on my own dataset. A temporal solution would be modifying the name for the generator that you will be using for the one direction test, or change line 23 of one_direction_test_model.lua to match the generator's name.
