### ISSUE TITLE
identity loss parameter

### ISSUE THREAD

**Issue by eturner303** [junyanz/CycleGAN#7]
Is there a way to configure the identity loss weight via the options parameters?  For instance, to set to 0.5 per some of the experiments in the paper?

I see a flag for enabling/disabling identity mapping but nothing for setting the loss weight

**Comment by taesung89** [comment]
Thanks for pointing that out. I just added the requested feature. 

Now the option identity.opt can work as a scalar rather than just binary 0 and 1. 

Setting opt.identity other than 1 has an effect of scaling the weight of the identity mapping loss by the specified amount. For example, if you want the reconstruction weight loss to be 5 and the identity mapping loss to be 0.5, please set `opt.lambda_A=5 opt.lambda_B=5 opt.identity=0.1`. 

To disable the identity mapping loss, you can still set it to 0.
